--------------------------------------------------------
--  File created - Monday-August-17-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ACCOUNTS
--------------------------------------------------------

  CREATE TABLE "TESTDB"."ACCOUNTS" 
   (	"ACCT_ID" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"INIT_BAL" NUMBER(20,4), 
	"BIRTHDATE" DATE, 
	"ACCT_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "TESTDB"."TRANSACTIONS" 
   (	"TRAN_ID" NUMBER(*,0), 
	"ACCT_ID" VARCHAR2(50 BYTE), 
	"AMOUNT" NUMBER(20,4), 
	"TRAN_DATE" DATE, 
	"TRAN_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TESTDB.ACCOUNTS
SET DEFINE OFF;
Insert into TESTDB.ACCOUNTS (ACCT_ID,NAME,INIT_BAL,BIRTHDATE,ACCT_TYPE) values ('888S','pure',520,to_date('05-MAY-00','DD-MON-RR'),'Savings');
Insert into TESTDB.ACCOUNTS (ACCT_ID,NAME,INIT_BAL,BIRTHDATE,ACCT_TYPE) values ('555S','alice',290,to_date('06-MAY-00','DD-MON-RR'),'Savings');
Insert into TESTDB.ACCOUNTS (ACCT_ID,NAME,INIT_BAL,BIRTHDATE,ACCT_TYPE) values ('66666','ankushi',0,to_date('08-APR-15','DD-MON-RR'),'Checking');
Insert into TESTDB.ACCOUNTS (ACCT_ID,NAME,INIT_BAL,BIRTHDATE,ACCT_TYPE) values ('4444','leaf',980,to_date('05-MAY-00','DD-MON-RR'),'Checking');
Insert into TESTDB.ACCOUNTS (ACCT_ID,NAME,INIT_BAL,BIRTHDATE,ACCT_TYPE) values ('66666S','Ankushi',99585,to_date('08-APR-15','DD-MON-RR'),'Savings');
Insert into TESTDB.ACCOUNTS (ACCT_ID,NAME,INIT_BAL,BIRTHDATE,ACCT_TYPE) values ('555','alice',4940,to_date('06-MAY-00','DD-MON-RR'),'Checking');
REM INSERTING into TESTDB.TRANSACTIONS
SET DEFINE OFF;
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (35,'555',50,to_date('04-MAY-14','DD-MON-RR'),'cs');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (37,'555',10,to_date('03-MAR-14','DD-MON-RR'),'cs');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (53,'4444',-20,to_date('05-AUG-14','DD-MON-RR'),'w');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (54,'888S',500,to_date('01-SEP-14','DD-MON-RR'),'dep');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (55,'66666',-1000,to_date('07-AUG-01','DD-MON-RR'),'w');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (31,'555',50,to_date('04-MAY-14','DD-MON-RR'),'cs');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (32,'555',50,to_date('04-MAY-14','DD-MON-RR'),'cs');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (36,'555',10,to_date('08-APR-13','DD-MON-RR'),'cs');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (38,'555',20,to_date('07-JUL-14','DD-MON-RR'),'cs');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (39,'555',20,to_date('05-MAY-10','DD-MON-RR'),'cs');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (33,'555',50,to_date('04-MAY-14','DD-MON-RR'),'cs');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (34,'555S',50,to_date('04-MAY-14','DD-MON-RR'),'sc');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (40,'555',10,to_date('04-APR-14','DD-MON-RR'),'cs');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (41,'555',-20,to_date('03-APR-13','DD-MON-RR'),'cs');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (42,'555',-10,to_date('04-APR-13','DD-MON-RR'),'cs');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (44,'888',-10,to_date('06-MAY-14','DD-MON-RR'),'CS');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (47,'88',5,to_date('05-APR-13','DD-MON-RR'),'CS');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (48,'555S',20,to_date('04-APR-14','DD-MON-RR'),'sc');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (49,'88',5,to_date('04-APR-14','DD-MON-RR'),'cs');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (46,'555',10,to_date('04-APR-15','DD-MON-RR'),'CS');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (50,'555S',10,to_date('04-APR-14','DD-MON-RR'),'sc');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (51,'888',10,to_date('04-APR-14','DD-MON-RR'),'cs');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (43,'555',-10,to_date('09-SEP-12','DD-MON-RR'),'cs');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (45,'888S',10,to_date('04-APR-13','DD-MON-RR'),'SC');
Insert into TESTDB.TRANSACTIONS (TRAN_ID,ACCT_ID,AMOUNT,TRAN_DATE,TRAN_TYPE) values (52,'888',-10,to_date('07-MAY-15','DD-MON-RR'),'d');
--------------------------------------------------------
--  DDL for Index SYS_C007305
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."SYS_C007305" ON "TESTDB"."ACCOUNTS" ("ACCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007306
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."SYS_C007306" ON "TESTDB"."TRANSACTIONS" ("TRAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."ACCOUNTS" ADD PRIMARY KEY ("ACCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."TRANSACTIONS" ADD PRIMARY KEY ("TRAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
